modLoader="javafml"
loaderVersion="[1,)"
license="CC0-1.0"

[properties]
"connector:placeholder"=true

[[mods]]
modId="settlement_roads"
version="2.0.1"
displayName="Countered's Settlement Roads"
authors="Countered"
description='''A mod that generates roads between villages'''

[[dependencies.settlement_roads]]
modId="neoforge"
mandatory=true
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.settlement_roads]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.settlement_roads]]
modId="connector"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"